services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend  # Point to backend directory
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env  # Path to .env file in backend directory
    environment:
      - PYTHONUNBUFFERED=1  # Disable Python output buffering=value
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: